import { GeneratorOptions } from '@prisma/generator-helper';
import * as fs from 'fs';
import * as path from 'path';
import { buildClientMeta, ClientMeta } from './metadata';
import { RUNTIME_SOURCE } from './runtime';
import { generateTypes } from './type-mapper';

const SUPPORTED_PROVIDERS = ['mysql'];

export function assertMysqlProvider(options: Pick<GeneratorOptions, 'datasources'>): void {
    const provider = options.datasources?.[0]?.activeProvider;
    if (!provider || !SUPPORTED_PROVIDERS.includes(provider)) {
        throw new Error(`prisma-lean only supports the "mysql" datasource provider (found "${provider ?? 'none'}").`);
    }
}

/** Generates the CommonJS implementation (`index.js`). */
export function generateJs(meta: ClientMeta): string {
    const enums = Object.fromEntries(meta.enums.map((e) => [e.name, Object.fromEntries(e.values.map((v) => [v, v]))]));

    return [
        '// AUTO-GENERATED BY PRISMA-LEAN. DO NOT EDIT.',
        "'use strict';",
        "const mysql = require('mysql2/promise');",
        "const crypto = require('node:crypto');",
        '',
        `const models = ${JSON.stringify(meta.models, null, 2)};`,
        RUNTIME_SOURCE,
        ...Object.entries(enums).map(([name, values]) => `exports.${name} = Object.freeze(${JSON.stringify(values)});`),
        'exports.LeanClient = LeanClient;',
        'exports.defaultPoolOptions = defaultPoolOptions;',
        '',
    ].join('\n');
}

export async function generateClient(options: GeneratorOptions) {
    const outputDir = options.generator.output?.value;
    if (!outputDir) throw new Error('No output path specified');

    assertMysqlProvider(options);

    const meta = buildClientMeta(options.dmmf);

    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(path.join(outputDir, 'index.js'), generateJs(meta));
    fs.writeFileSync(path.join(outputDir, 'index.d.ts'), generateTypes(meta));
    removeLegacyOutput(path.join(outputDir, 'index.ts'));
}

/** Older prisma-lean versions wrote `index.ts`, which would shadow the new `index.js`. */
function removeLegacyOutput(file: string) {
    if (!fs.existsSync(file)) return;
    if (fs.readFileSync(file, 'utf8').startsWith('// AUTO-GENERATED BY PRISMA-LEAN')) fs.rmSync(file);
}
