import { ClientMeta, FieldMeta, ModelMeta } from './metadata';

export type TypeMode = 'output' | 'input';

/**
 * Maps a Prisma scalar type to the TypeScript type the generated client uses.
 *
 * `output` is what the client returns (after row mapping). `input` is what the
 * client accepts in `create`, `update` and `where`.
 */
export function mapPrismaTypeToTS(fieldType: string, mode: TypeMode = 'output'): string {
    switch (fieldType) {
        case 'String':
            return 'string';
        case 'Int':
        case 'Float':
            return 'number';
        case 'Decimal':
            // Returned as a string to keep precision.
            return mode === 'input' ? 'string | number' : 'string';
        case 'BigInt':
            return mode === 'input' ? 'bigint | number' : 'bigint';
        case 'Boolean':
            return 'boolean';
        case 'DateTime':
            return 'Date';
        case 'Json':
            return 'JsonValue';
        case 'Bytes':
            return mode === 'input' ? 'Uint8Array' : 'Buffer';
        default:
            return 'unknown';
    }
}

function fieldType(field: FieldMeta, mode: TypeMode): string {
    return field.kind === 'enum' ? field.type : mapPrismaTypeToTS(field.type, mode);
}

function nullable(field: FieldMeta, type: string): string {
    return field.isRequired ? type : `${type} | null`;
}

function isOptionalOnCreate(field: FieldMeta): boolean {
    return !field.isRequired || field.default !== null || field.isDbGenerated || field.isUpdatedAt;
}

function block(header: string, lines: string[]): string {
    return [`${header} {`, ...lines.map((l) => `  ${l}`), '}', ''].join('\n');
}

function modelTypes(model: ModelMeta): string {
    const { name } = model;
    const out: string[] = [];

    out.push(
        block(
            `export interface ${name}`,
            model.fields.map((f) => `${f.name}: ${nullable(f, fieldType(f, 'output'))};`),
        ),
    );

    out.push(
        block(
            `export interface ${name}CreateInput`,
            model.fields.map(
                (f) => `${f.name}${isOptionalOnCreate(f) ? '?' : ''}: ${nullable(f, fieldType(f, 'input'))};`,
            ),
        ),
    );

    out.push(
        block(
            `export interface ${name}UpdateInput`,
            model.fields.map((f) => `${f.name}?: ${nullable(f, fieldType(f, 'input'))};`),
        ),
    );

    // Json columns cannot be compared with `=` reliably, so they are not filterable.
    const filterable = model.fields.filter((f) => f.type !== 'Json');
    out.push(
        block(
            `export interface ${name}WhereInput`,
            filterable.map((f) => `${f.name}?: ${nullable(f, fieldType(f, 'input'))};`),
        ),
    );

    out.push(`export type ${name}OrderByInput = { [K in keyof ${name}]?: SortOrder };\n`);

    if (model.uniqueKeys.length > 0) {
        const byName = new Map(model.fields.map((f) => [f.name, f]));
        const variants = model.uniqueKeys.map((key) => {
            if (key.fields.length === 1 && key.name === key.fields[0]) {
                const f = byName.get(key.name)!;
                return `{ ${f.name}: ${fieldType(f, 'input')} }`;
            }
            const inner = key.fields.map((n) => `${n}: ${fieldType(byName.get(n)!, 'input')}`).join('; ');
            return `{ ${key.name}: { ${inner} } }`;
        });
        out.push(`export type ${name}WhereUniqueInput = ${variants.join(' | ')};\n`);
    }

    const methods: string[] = [];
    if (model.uniqueKeys.length > 0) {
        methods.push(`findUnique(args: { where: ${name}WhereUniqueInput }): Promise<${name} | null>;`);
    }
    methods.push(
        `findMany(args?: { where?: ${name}WhereInput; orderBy?: ${name}OrderByInput | ${name}OrderByInput[]; take?: number; skip?: number }): Promise<${name}[]>;`,
    );
    methods.push(`count(args?: { where?: ${name}WhereInput }): Promise<number>;`);
    methods.push(`create(args: { data: ${name}CreateInput }): Promise<${name}>;`);
    if (model.uniqueKeys.length > 0) {
        methods.push(`update(args: { where: ${name}WhereUniqueInput; data: ${name}UpdateInput }): Promise<${name}>;`);
        methods.push(`delete(args: { where: ${name}WhereUniqueInput }): Promise<${name}>;`);
    }
    out.push(block(`export interface ${name}Delegate`, methods));

    return out.join('\n');
}

/** Generates the full `index.d.ts` for the client. */
export function generateTypes(meta: ClientMeta): string {
    const out: string[] = [
        '// AUTO-GENERATED BY PRISMA-LEAN. DO NOT EDIT.',
        "import type { Pool, PoolOptions } from 'mysql2/promise';",
        '',
        'export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };',
        "export type SortOrder = 'asc' | 'desc';",
        '',
    ];

    for (const e of meta.enums) {
        out.push(`export type ${e.name} = ${e.values.map((v) => JSON.stringify(v)).join(' | ')};`);
        out.push(
            `export declare const ${e.name}: { ${e.values.map((v) => `readonly ${v}: ${JSON.stringify(v)}`).join('; ')} };`,
        );
        out.push('');
    }

    for (const model of meta.models) out.push(modelTypes(model));

    const accessors = meta.models.map((m) => `readonly ${m.accessor}: ${m.name}Delegate;`);
    out.push(block('export interface LeanTransactionClient', accessors));
    out.push(
        '/** Pool options applied when LeanClient creates the pool. Pass them too when you create your own pool. */',
    );
    out.push('export declare const defaultPoolOptions: PoolOptions;\n');
    out.push(
        block('export declare class LeanClient implements LeanTransactionClient', [
            'constructor(config: string | PoolOptions | Pool);',
            ...accessors,
            '/** Runs `fn` in a transaction. Commits when `fn` resolves, rolls back when it throws. */',
            '$transaction<T>(fn: (tx: LeanTransactionClient) => Promise<T>): Promise<T>;',
            '/** Closes the connection pool. */',
            '$disconnect(): Promise<void>;',
        ]),
    );

    return out.join('\n');
}
